kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: operator-shared-pvc
  namespace: ier
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi